@startuml
start
:Клиент создает заказ;

if (Все ингредиенты в наличии?) then (да)
  :Заказ сохранен в системе;
  :Клиент переходит к оплате;
  
  if (Оплата успешна?) then (да)
    :Заказ передан в очередь бариста;
    :Бариста подтверждает начало приготовления;
    :Бариста готовит и отмечает "Готово";
    :Система уведомляет клиента;
    :Клиент забирает заказ;
  else (нет)
    :Система показывает ошибку оплаты;
    :Предложить повторить или сменить способ;
    stop
  endif
  
else (нет)
  :Система уведомляет: "Ингредиент закончился";
  :Предложить аналогичный напиток;
  stop
endif

stop
@enduml